### ISSUE TITLE
Sometimes sava returns 503 on DC/OS on Azure.

### ISSUE THREAD

**Issue by bufferings** [magneticio/vamp-gateway-agent#24]
Sava sometimes returns 503 for some resources randomly like this picture. It sometimes return 200 and sometimes returns 503 even it's the main html file.

![2016-10-29_1755](https://cloud.githubusercontent.com/assets/763849/19828453/f893e87c-9e00-11e6-88b2-3d0caf49d398.png)

I'm doubting something happen with VGA, because it always returns 200 when I upload Sava image on Marathon directly. I'm glad if you kindly let me know what I should check?

I deployed sava with following blueprint, only modifying port to 80 from 9050.

```

---
name: sava:1.0
gateways:
  80: sava/webport
clusters:
  sava:
    services:
      breed:
        name: sava:1.0.0
        deployable: magneticio/sava:1.0.0
        ports:
          webport: 8080/http
      scale:
        cpu: 0.2       
        memory: 64MB
        instances: 1
```

I installed vamp on Azure DC/OS following this document.
http://vamp.io/documentation/installation/dcos/

I use 1 public agent and 2 private agents. So I have 3 VGAs.

```
Hi, I'm Vamp! How are you? 

RUNNING SINCE   29-10-2016 17:38:00
VERSION 0.9.0-65-g1ccc425
UI VERSION  0.9.0-107-g8186782
PERSISTENCE elasticsearch
KEY VALUE STORE zookeeper
GATEWAY DRIVER  haproxy 1.6.x
CONTAINER DRIVER    marathon
WORKFLOW DRIVER marathon
```

```
Marathon Details

Version
1.3.0
```

```
$ dcos --version
dcoscli.version=0.4.12
dcos.version=1.8.4
dcos.commit=e64024af95b62c632c90b9063ed06296fcf38ea5
dcos.bootstrap-id=5b4aa43610c57ee1d60b4aa0751a1fb75824c083
```
